var aliases = {
	"langToCode": {
		"English KJV": {
			"1 Samuel.": "1SA",
			"Jonah.": "JON",
			"THE SECOND EPISTLE OF JOHN.": "2JN",
			"Mark.": "MRK",
			"Haggai.": "HAG",
			"1 Timothy.": "1TI",
			"Job.": "JOB",
			"Jeremiah.": "JER",
			"Joshua.": "JOS",
			"Zechariah.": "ZEC",
			"Revelation.": "REV",
			"Nahum.": "NAM",
			"Hebrews.": "HEB",
			"Daniel.": "DAN",
			"Joel.": "JOL",
			"Titus.": "TIT",
			"John.": "JHN",
			"Numbers.": "NUM",
			"Luke.": "LUK",
			"Habakkuk.": "HAB",
			"1 Kings.": "1KI",
			"Judges.": "JDG",
			"Philippians.": "PHP",
			"Amos.": "AMO",
			"Micah.": "MIC",
			"1 Peter.": "1PE",
			"THE GENERAL EPISTLE OF JUDE.": "JUD",
			"Esther.": "EST",
			"THE EPISTLE OF PAUL THE APOSTLE TO PHILEMON.": "PHM",
			"Psalms.": "PSA",
			"Galatians.": "GAL",
			"2 Samuel.": "2SA",
			"1 John.": "1JN",
			"Hosea.": "HOS",
			"Ruth.": "RUT",
			"Song of Solomon.": "SNG",
			"Ezekiel.": "EZK",
			"Acts.": "ACT",
			"Lamentations.": "LAM",
			"Ephesians.": "EPH",
			"Isaiah.": "ISA",
			"James.": "JAS",
			"Proverbs.": "PRO",
			"Leviticus.": "LEV",
			"2 Corinthians.": "2CO",
			"1 Corinthians.": "1CO",
			"2 Thessalonians.": "2TH",
			"Obadiah.": "OBA",
			"Ecclesiastes.": "ECC",
			"Genesis.": "GEN",
			"2 Timothy.": "2TI",
			"Zephaniah.": "ZEP",
			"THE THIRD EPISTLE OF JOHN.": "3JN",
			"Romans.": "ROM",
			"Ezra.": "EZR",
			"1 Thessalonians.": "1TH",
			"Colossians.": "COL",
			"2 Chronicles.": "2CH",
			"Nehemiah.": "NEH",
			"Malachi.": "MAL",
			"Matthew.": "MAT",
			"Exodus.": "EXO",
			"2 Kings.": "2KI",
			"Deuteronomy.": "DEU",
			"2 Peter.": "2PE",
			"1 Chronicles.": "1CH"
		},
		"English WEB": {
			"1 Samuel.": "1SA",
			"Jonah.": "JON",
			"Mark.": "MRK",
			"Haggai.": "HAG",
			"1 Timothy.": "1TI",
			"Job.": "JOB",
			"Jeremiah.": "JER",
			"Joshua.": "JOS",
			"Zechariah.": "ZEC",
			"Revelation.": "REV",
			"Nahum.": "NAM",
			"Hebrews.": "HEB",
			"Daniel.": "DAN",
			"Joel.": "JOL",
			"Titus.": "TIT",
			"John.": "JHN",
			"Numbers.": "NUM",
			"Luke.": "LUK",
			"Habakkuk.": "HAB",
			"1 Kings.": "1KI",
			"Judges.": "JDG",
			"Philippians.": "PHP",
			"Amos.": "AMO",
			"Micah.": "MIC",
			"1 Peter.": "1PE",
			"Esther.": "EST",
			"Psalms.": "PSA",
			"Galatians.": "GAL",
			"2 Samuel.": "2SA",
			"1 John.": "1JN",
			"Hosea.": "HOS",
			"Ruth.": "RUT",
			"Song of Solomon.": "SNG",
			"Ezekiel.": "EZK",
			"Acts.": "ACT",
			"John’s Third Letter.": "3JN",
			"Lamentations.": "LAM",
			"Ephesians.": "EPH",
			"Isaiah.": "ISA",
			"James.": "JAS",
			"Proverbs.": "PRO",
			"Leviticus.": "LEV",
			"2 Corinthians.": "2CO",
			"1 Corinthians.": "1CO",
			"2 Thessalonians.": "2TH",
			"Ecclesiastes.": "ECC",
			"Paul’s Letter to Philemon.": "PHM",
			"Genesis.": "GEN",
			"2 Timothy.": "2TI",
			"Zephaniah.": "ZEP",
			"Romans.": "ROM",
			"Ezra.": "EZR",
			"The Letter from Jude.": "JUD",
			"1 Thessalonians.": "1TH",
			"Colossians.": "COL",
			"John’s Second Letter.": "2JN",
			"2 Chronicles.": "2CH",
			"Nehemiah.": "NEH",
			"Malachi.": "MAL",
			"Matthew.": "MAT",
			"Exodus.": "EXO",
			"2 Kings.": "2KI",
			"Deuteronomy.": "DEU",
			"The Book of Obadiah.": "OBA",
			"2 Peter.": "2PE",
			"1 Chronicles.": "1CH"
		},
		"新标点和合本": {
			"箴言.": "PRO",
			"腓利门书.": "PHM",
			"尼希米记.": "NEH",
			"以斯帖记.": "EST",
			"约书亚记.": "JOS",
			"约珥书.": "JOL",
			"以西结书.": "EZK",
			"列王纪上.": "1KI",
			"约翰三书.": "3JN",
			"民数记.": "NUM",
			"阿摩司书.": "AMO",
			"马可福音.": "MRK",
			"创世记.": "GEN",
			"历代志下.": "2CH",
			"罗马书.": "ROM",
			"马太福音.": "MAT",
			"约翰福音.": "JHN",
			"耶利米哀歌.": "LAM",
			"那鸿书.": "NAM",
			"撒母耳记下.": "2SA",
			"彼得前书.": "1PE",
			"雅歌.": "SNG",
			"歌罗西书.": "COL",
			"利未记.": "LEV",
			"启示录.": "REV",
			"约翰一书.": "1JN",
			"提摩太前书.": "1TI",
			"路加福音.": "LUK",
			"申命记.": "DEU",
			"提摩太后书.": "2TI",
			"使徒行传.": "ACT",
			"撒母耳记上.": "1SA",
			"诗篇.": "PSA",
			"哈该书.": "HAG",
			"耶利米书.": "JER",
			"约翰二书.": "2JN",
			"约伯记.": "JOB",
			"弥迦书.": "MIC",
			"以弗所书.": "EPH",
			"帖撒罗尼迦后书.": "2TH",
			"何西阿书.": "HOS",
			"西番雅书.": "ZEP",
			"哥林多前书.": "1CO",
			"哈巴谷书.": "HAB",
			"以斯拉记.": "EZR",
			"腓立比书.": "PHP",
			"彼得后书.": "2PE",
			"传道书.": "ECC",
			"提多书.": "TIT",
			"士师记.": "JDG",
			"玛拉基书.": "MAL",
			"犹大书.": "JUD",
			"雅各书.": "JAS",
			"哥林多后书.": "2CO",
			"俄巴底亚书.": "OBA",
			"帖撒罗尼迦前书.": "1TH",
			"约拿书.": "JON",
			"列王纪下.": "2KI",
			"历代志上.": "1CH",
			"撒迦利亚书.": "ZEC",
			"路得记.": "RUT",
			"以赛亚书.": "ISA",
			"但以理书.": "DAN",
			"出埃及记.": "EXO",
			"加拉太书.": "GAL",
			"希伯来书.": "HEB"
		},
		"सरल हिन्दी बाइबल": {
			"लेवी.": "LEV",
			"यहेजकेल.": "EZK",
			"होशेआ.": "HOS",
			"2 थेस्सलोनि.": "2TH",
			"1 इतिहास.": "1CH",
			"यहोशू.": "JOS",
			"अय्योब.": "JOB",
			"ओबदयाह.": "OBA",
			"2 पेतरॉस.": "2PE",
			"योहन का दूसरा पत्र.": "2JN",
			"व्यवस्था.": "DEU",
			"नहूम.": "NAM",
			"गलातिया.": "GAL",
			"गणना.": "NUM",
			"मलाकी.": "MAL",
			"जेफ़नयाह.": "ZEP",
			"याकोब.": "JAS",
			"एज़्रा.": "EZR",
			"स्तोत्र.": "PSA",
			"प्रशासक.": "JDG",
			"मत्तियाह.": "MAT",
			"रोमियों.": "ROM",
			"इब्री.": "HEB",
			"1 तिमोथियॉस.": "1TI",
			"फ़िलेमोन के नाम पौलॉस का पत्र.": "PHM",
			"1 योहन.": "1JN",
			"येरेमियाह.": "JER",
			"विलापगीत.": "LAM",
			"2 शमुएल.": "2SA",
			"1 कोरिंथ.": "1CO",
			"कोलोस्सॉय.": "COL",
			"योहन का तीसरा पत्र.": "3JN",
			"उद्बोधक.": "ECC",
			"लूकॉस.": "LUK",
			"सर्वश्रेष्ठ गीत.": "SNG",
			"1 राजा.": "1KI",
			"योनाह.": "JON",
			"दानिएल.": "DAN",
			"1 पेतरॉस.": "1PE",
			"प्रेरितों.": "ACT",
			"योहन.": "JHN",
			"तीतॉस.": "TIT",
			"योएल.": "JOL",
			"मीकाह.": "MIC",
			"फ़िलिप्पॉय.": "PHP",
			"यशायाह.": "ISA",
			"मार्कास.": "MRK",
			"2 तिमोथियॉस.": "2TI",
			"नेहेमियाह.": "NEH",
			"हबक्कूक.": "HAB",
			"इफ़ेसॉस.": "EPH",
			"2 कोरिंथ.": "2CO",
			"यहूदाह का पत्र.": "JUD",
			"एस्तेर.": "EST",
			"2 इतिहास.": "2CH",
			"आमोस.": "AMO",
			"ज़करयाह.": "ZEC",
			"उत्पत्ति.": "GEN",
			"1 शमुएल.": "1SA",
			"रूथ.": "RUT",
			"हाग्गय.": "HAG",
			"निर्गमन.": "EXO",
			"2 राजा.": "2KI",
			"सूक्ति संग्रह.": "PRO",
			"1 थेस्सलोनि.": "1TH",
			"प्रकाशन.": "REV"
		},
		"Santa Biblia libre para el mundo": {
			"SOFONÍAS.": "ZEP",
			"HAGEO.": "HAG",
			"1 TESALONICENSES.": "1TH",
			"CANTARES.": "SNG",
			"ROMANOS.": "ROM",
			"ESTER.": "EST",
			"PROVERBIOS.": "PRO",
			"1 REYES.": "1KI",
			"2 REYES.": "2KI",
			"NEHEMÍAS.": "NEH",
			"LA CARTA UNIVERSAL DE SAN JUDAS APÓSTOL.": "JUD",
			"SAN LUCAS.": "LUK",
			"DEUTERONOMIO.": "DEU",
			"JOB.": "JOB",
			"ESDRAS.": "EZR",
			"1 CRÓNICAS.": "1CH",
			"EL APOCALIPSIS.": "REV",
			"AMÓS.": "AMO",
			"SAN MARCOS.": "MRK",
			"ISAÍAS.": "ISA",
			"NÚMEROS.": "NUM",
			"2 TIMOTEO.": "2TI",
			"1 JUAN.": "1JN",
			"ABDÍAS.": "OBA",
			"FILIPENSES.": "PHP",
			"HABACUC.": "HAB",
			"JOEL.": "JOL",
			"JONÁS.": "JON",
			"ZACARÍAS.": "ZEC",
			"MALAQUÍAS.": "MAL",
			"HECHOS.": "ACT",
			"2 SAMUEL.": "2SA",
			"OSEAS.": "HOS",
			"TITO.": "TIT",
			"JEREMÍAS.": "JER",
			"1 PEDRO.": "1PE",
			"SAN JUAN.": "JHN",
			"2 PEDRO.": "2PE",
			"ECLESIASTÉS.": "ECC",
			"GÁLATAS.": "GAL",
			"1 CORINTIOS.": "1CO",
			"2 CRÓNICAS.": "2CH",
			"LAMENTACIONES.": "LAM",
			"NAHUM.": "NAM",
			"LEVÍTICO.": "LEV",
			"COLOSENSES.": "COL",
			"HEBREOS.": "HEB",
			"SEGUNDA CARTA DE SAN JUAN APÓSTOL.": "2JN",
			"SAN MATEO.": "MAT",
			"TERCERA CARTA DE SAN JUAN APÓSTOL.": "3JN",
			"1 TIMOTEO.": "1TI",
			"EZEQUIEL.": "EZK",
			"LA CARTA DEL APÓSTOL SAN PABLO A FILEMÓN.": "PHM",
			"SANTIAGO.": "JAS",
			"EFESIOS.": "EPH",
			"JOSUÉ.": "JOS",
			"GÉNESIS.": "GEN",
			"DANIEL.": "DAN",
			"1 SAMUEL.": "1SA",
			"JUECES.": "JDG",
			"ÉXODO.": "EXO",
			"SALMOS.": "PSA",
			"2 CORINTIOS.": "2CO",
			"RUT.": "RUT",
			"2 TESALONICENSES.": "2TH",
			"MIQUEAS.": "MIC"
		},
		"Sainte Bible libre pour le monde": {
			"1 Samuel.": "1SA",
			"Jacques.": "JAS",
			"Juges.": "JDG",
			"Marc.": "MRK",
			"La lettre de Paul à Philémon.": "PHM",
			"1 Pierre.": "1PE",
			"Numéros.": "NUM",
			"Hébreux.": "HEB",
			"Néhémie.": "NEH",
			"Ézéchiel.": "EZK",
			"Philippiens.": "PHP",
			"Sophonie.": "ZEP",
			"1 Chroniques.": "1CH",
			"La troisième lettre de Jean.": "3JN",
			"Job.": "JOB",
			"1 Timothée.": "1TI",
			"2 Rois.": "2KI",
			"Le livre du prophète Abdias.": "OBA",
			"Actes.": "ACT",
			"Osée.": "HOS",
			"2 Corinthiens.": "2CO",
			"Joël.": "JOL",
			"Daniel.": "DAN",
			"Jean.": "JHN",
			"Cantique.": "SNG",
			"Nahoum.": "NAM",
			"Lévitique.": "LEV",
			"Deutéronome.": "DEU",
			"2 Chroniques.": "2CH",
			"Luc.": "LUK",
			"1 Thessaloniciens.": "1TH",
			"Galates.": "GAL",
			"Josué.": "JOS",
			"Malachie.": "MAL",
			"2 Timothée.": "2TI",
			"Éphésiens.": "EPH",
			"Amos.": "AMO",
			"Zacharie.": "ZEC",
			"Psaumes.": "PSA",
			"Matthieu.": "MAT",
			"2 Pierre.": "2PE",
			"Esther.": "EST",
			"Ecclésiaste.": "ECC",
			"Michée.": "MIC",
			"2 Samuel.": "2SA",
			"Genèse.": "GEN",
			"Colossiens.": "COL",
			"Ruth.": "RUT",
			"Romains.": "ROM",
			"Apocalypse.": "REV",
			"Lamentations.": "LAM",
			"1 Corinthiens.": "1CO",
			"Aggée.": "HAG",
			"1 Jean.": "1JN",
			"Exode.": "EXO",
			"Esdras.": "EZR",
			"Ésaïe.": "ISA",
			"Habacuc.": "HAB",
			"Jonas.": "JON",
			"Proverbes.": "PRO",
			"La lettre de Jude.": "JUD",
			"Jérémie.": "JER",
			"La deuxième lettre de Jean.": "2JN",
			"2 Thessaloniciens.": "2TH",
			"Tite.": "TIT",
			"1 Rois.": "1KI"
		},
		"كتاب الحياة": {
			"هُوشَع.": "HOS",
			"أعمال.": "ACT",
			"أيُّوب.": "JOB",
			"دانيال.": "DAN",
			"خرُوج.": "EXO",
			"لُوقا.": "LUK",
			"1 مُلُوك.": "1KI",
			"رسالَةُ يَهُوذا.": "JUD",
			"مزمور.": "PSA",
			"ميخا.": "MIC",
			"إرْمِيا.": "JER",
			"زَكَريّا.": "ZEC",
			"2 كورنثوس.": "2CO",
			"كتابُ عُوبَدْيا.": "OBA",
			"2 تسالونيكي.": "2TH",
			"يَعقُوب.": "JAS",
			"الرِّسالَةُ إلَى فِلِيْمُون.": "PHM",
			"إشَعْياء.": "ISA",
			"صَفَنْيا.": "ZEP",
			"مَلاخِي.": "MAL",
			"نَحَمْيا.": "NEH",
			"غَلاطِيَّة.": "GAL",
			"1 أخبار.": "1CH",
			"رُؤيا.": "REV",
			"رسالَةُ يُوحَنّا الثّالثَة.": "3JN",
			"2 تيموثاوس.": "2TI",
			"ناحُوم.": "NAM",
			"1 صَمُوئيل.": "1SA",
			"1 كورنثوس.": "1CO",
			"تِيطُس.": "TIT",
			"أمثال.": "PRO",
			"تَثنِيَة.": "DEU",
			"1 تسالونيكي.": "1TH",
			"2 مُلُوك.": "2KI",
			"حَجَّي.": "HAG",
			"عَدَد.": "NUM",
			"يُوئيل.": "JOL",
			"1 يوحنَّا.": "1JN",
			"2 بطرس.": "2PE",
			"مَتَّى.": "MAT",
			"يَشُوع.": "JOS",
			"نشِيد.": "SNG",
			"فِيلِبِّي.": "PHP",
			"يوحنَّا.": "JHN",
			"راعُوث.": "RUT",
			"يُونان.": "JON",
			"قُضاة.": "JDG",
			"2 صَمُوئيل.": "2SA",
			"مَرْقُس.": "MRK",
			"رُوما.": "ROM",
			"جامِعَة.": "ECC",
			"حِزْقِيال.": "EZK",
			"1 تيموثاوس.": "1TI",
			"تكوين.": "GEN",
			"حَبَقُّوق.": "HAB",
			"عِبرانِيّين.": "HEB",
			"أسْتِير.": "EST",
			"رسالَةُ يُوحَنّا الثّانِيَة.": "2JN",
			"كُولُوسِي.": "COL",
			"1 بطرس.": "1PE",
			"مَراثِي.": "LAM",
			"أفَسُس.": "EPH",
			"عَزْرا.": "EZR",
			"2 أخبار.": "2CH",
			"عامُوس.": "AMO",
			"لاويّين.": "LEV"
		},
		"ইন্ডিয়ান রিভাইজড ভার্সন": {
			"ফিলিপীয়.": "PHP",
			"যিহূদা.": "JUD",
			"যোহন.": "JHN",
			"1 রাজাবলি.": "1KI",
			"রূত.": "RUT",
			"1 পিতর.": "1PE",
			"প্রকাশিত বাক্য.": "REV",
			"হোশেয়.": "HOS",
			"হিতোপদেশ.": "PRO",
			"1 তীমথিয়.": "1TI",
			"দানিয়েল.": "DAN",
			"যিহোশূয়.": "JOS",
			"তীত.": "TIT",
			"লেবীয়.": "LEV",
			"যাত্রাপুস্তক.": "EXO",
			"বিলাপ.": "LAM",
			"হগয়.": "HAG",
			"2 করিন্থীয়.": "2CO",
			"ফিলীমন.": "PHM",
			"পরমগীত.": "SNG",
			"আদিপুস্তক.": "GEN",
			"প্রেরিতদের কার্য্য.": "ACT",
			"2 যোহন.": "2JN",
			"হবককূক.": "HAB",
			"নহিমিয়.": "NEH",
			"মার্ক.": "MRK",
			"যিহিস্কেল.": "EZK",
			"আমোষ.": "AMO",
			"2 থিষলনীকীয়.": "2TH",
			"গীতসংহিতা.": "PSA",
			"যোয়েল.": "JOL",
			"যাকোব.": "JAS",
			"2 তীমথিয়.": "2TI",
			"উপদেশক.": "ECC",
			"1 করিন্থীয়.": "1CO",
			"গণনা.": "NUM",
			"লুক.": "LUK",
			"কলসীয়.": "COL",
			"ইষ্টের.": "EST",
			"1 থিষলনীকীয়.": "1TH",
			"2 শমূয়েল.": "2SA",
			"ইফিষীয়.": "EPH",
			"রোমীয়.": "ROM",
			"মথি.": "MAT",
			"মীখা.": "MIC",
			"2 রাজাবলি.": "2KI",
			"3 যোহন.": "3JN",
			"বিচারকর্ত্তৃগণ.": "JDG",
			"যোনা.": "JON",
			"মালাখি.": "MAL",
			"ইয়োব.": "JOB",
			"2 বংশাবলি.": "2CH",
			"2 পিতর.": "2PE",
			"দ্বিতীয় বিবরণ.": "DEU",
			"সখরিয়.": "ZEC",
			"1 যোহন.": "1JN",
			"1 শমূয়েল.": "1SA",
			"নহূম.": "NAM",
			"গালাতীয়.": "GAL",
			"সফনিয়.": "ZEP",
			"ইব্রীয়.": "HEB",
			"যিরমিয়.": "JER",
			"যিশাইয়.": "ISA",
			"ওবদিয়.": "OBA",
			"1 বংশাবলি.": "1CH",
			"ইষ্রা.": "EZR"
		},
		"Синодальный перевод": {
			"Второзаконие.": "DEU",
			"Второе послание Петра.": "2PE",
			"Книга пророка Ионы.": "JON",
			"Послание к Римлянам.": "ROM",
			"Первое послание к Коринфянам.": "1CO",
			"Евангелие от Матфея.": "MAT",
			"Послание к Евреям.": "HEB",
			"Плач Иеремии.": "LAM",
			"Книга Иова.": "JOB",
			"Откровение Иоанна Богослова.": "REV",
			"Деяния.": "ACT",
			"Книга Иисуса Навина.": "JOS",
			"Книга пророка Авдия.": "OBA",
			"Третье послание Иоанна.": "3JN",
			"Песни Песней.": "SNG",
			"Неемия.": "NEH",
			"Второе послание к Фессалоникийцам.": "2TH",
			"Книга Екклесиаста.": "ECC",
			"Книга пророка Аввакума.": "HAB",
			"Книга пророка Иеремии.": "JER",
			"Книга пророка Иоиля.": "JOL",
			"Послание к Филимону.": "PHM",
			"Вторая книга Паралипоменон.": "2CH",
			"Евангелие от Луки.": "LUK",
			"Книга Руфь.": "RUT",
			"Исход.": "EXO",
			"Послание к Галатам.": "GAL",
			"Притчи Соломона.": "PRO",
			"Евангелие от Иоанна.": "JHN",
			"Послание к Титу.": "TIT",
			"Первое послание к Фессалоникийцам.": "1TH",
			"Евангелие от Марка.": "MRK",
			"Первая книга Паралипоменон.": "1CH",
			"Книга пророка Даниила.": "DAN",
			"Книга пророка Аггея.": "HAG",
			"Книга пророка Софонии.": "ZEP",
			"Книга пророка Малахии.": "MAL",
			"Бытие.": "GEN",
			"Второе послание Иоанна.": "2JN",
			"Послание Иакова.": "JAS",
			"Второе послание к Тимофею.": "2TI",
			"Четвертая книга Царств.": "2KI",
			"Книга Судей Израилевых.": "JDG",
			"Книга пророка Наума.": "NAM",
			"Послание к Филлиппийцам.": "PHP",
			"Книга пророка Исаии.": "ISA",
			"Первое послание Иоанна.": "1JN",
			"Вторая книга Царств.": "2SA",
			"Второе послание к Коринфянам.": "2CO",
			"Левит.": "LEV",
			"Послание к Колоссянам.": "COL",
			"Послание Иуды.": "JUD",
			"Книга пророка Осии.": "HOS",
			"Псалтырь.": "PSA",
			"Первое послание Петра.": "1PE",
			"Послание к Ефесянам.": "EPH",
			"Книга пророка Амоса.": "AMO",
			"Книга Есфирь.": "EST",
			"Книга пророка Михея.": "MIC",
			"Числа.": "NUM",
			"Третья книга Царств.": "1KI",
			"Первая книга Царств.": "1SA",
			"Первое послание к Тимофею.": "1TI",
			"Книга Ездры.": "EZR",
			"Книга пророка Иезекииля.": "EZK",
			"Книга пророка Захарии.": "ZEC"
		}
	},
	"codeToLang": {
		"English KJV": {
			"GEN": "Genesis.",
			"EXO": "Exodus.",
			"LEV": "Leviticus.",
			"NUM": "Numbers.",
			"DEU": "Deuteronomy.",
			"JOS": "Joshua.",
			"JDG": "Judges.",
			"RUT": "Ruth.",
			"1SA": "1 Samuel.",
			"2SA": "2 Samuel.",
			"1KI": "1 Kings.",
			"2KI": "2 Kings.",
			"1CH": "1 Chronicles.",
			"2CH": "2 Chronicles.",
			"EZR": "Ezra.",
			"NEH": "Nehemiah.",
			"EST": "Esther.",
			"JOB": "Job.",
			"PSA": "Psalms.",
			"PRO": "Proverbs.",
			"ECC": "Ecclesiastes.",
			"SNG": "Song of Solomon.",
			"ISA": "Isaiah.",
			"JER": "Jeremiah.",
			"LAM": "Lamentations.",
			"EZK": "Ezekiel.",
			"DAN": "Daniel.",
			"HOS": "Hosea.",
			"JOL": "Joel.",
			"AMO": "Amos.",
			"OBA": "Obadiah.",
			"JON": "Jonah.",
			"MIC": "Micah.",
			"NAM": "Nahum.",
			"HAB": "Habakkuk.",
			"ZEP": "Zephaniah.",
			"HAG": "Haggai.",
			"ZEC": "Zechariah.",
			"MAL": "Malachi.",
			"MAT": "Matthew.",
			"MRK": "Mark.",
			"LUK": "Luke.",
			"JHN": "John.",
			"ACT": "Acts.",
			"ROM": "Romans.",
			"1CO": "1 Corinthians.",
			"2CO": "2 Corinthians.",
			"GAL": "Galatians.",
			"EPH": "Ephesians.",
			"PHP": "Philippians.",
			"COL": "Colossians.",
			"1TH": "1 Thessalonians.",
			"2TH": "2 Thessalonians.",
			"1TI": "1 Timothy.",
			"2TI": "2 Timothy.",
			"TIT": "Titus.",
			"PHM": "THE EPISTLE OF PAUL THE APOSTLE TO PHILEMON.",
			"HEB": "Hebrews.",
			"JAS": "James.",
			"1PE": "1 Peter.",
			"2PE": "2 Peter.",
			"1JN": "1 John.",
			"2JN": "THE SECOND EPISTLE OF JOHN.",
			"3JN": "THE THIRD EPISTLE OF JOHN.",
			"JUD": "THE GENERAL EPISTLE OF JUDE.",
			"REV": "Revelation."
		},
		"English WEB": {
			"GEN": "Genesis.",
			"EXO": "Exodus.",
			"LEV": "Leviticus.",
			"NUM": "Numbers.",
			"DEU": "Deuteronomy.",
			"JOS": "Joshua.",
			"JDG": "Judges.",
			"RUT": "Ruth.",
			"1SA": "1 Samuel.",
			"2SA": "2 Samuel.",
			"1KI": "1 Kings.",
			"2KI": "2 Kings.",
			"1CH": "1 Chronicles.",
			"2CH": "2 Chronicles.",
			"EZR": "Ezra.",
			"NEH": "Nehemiah.",
			"EST": "Esther.",
			"JOB": "Job.",
			"PSA": "Psalms.",
			"PRO": "Proverbs.",
			"ECC": "Ecclesiastes.",
			"SNG": "Song of Solomon.",
			"ISA": "Isaiah.",
			"JER": "Jeremiah.",
			"LAM": "Lamentations.",
			"EZK": "Ezekiel.",
			"DAN": "Daniel.",
			"HOS": "Hosea.",
			"JOL": "Joel.",
			"AMO": "Amos.",
			"OBA": "The Book of Obadiah.",
			"JON": "Jonah.",
			"MIC": "Micah.",
			"NAM": "Nahum.",
			"HAB": "Habakkuk.",
			"ZEP": "Zephaniah.",
			"HAG": "Haggai.",
			"ZEC": "Zechariah.",
			"MAL": "Malachi.",
			"MAT": "Matthew.",
			"MRK": "Mark.",
			"LUK": "Luke.",
			"JHN": "John.",
			"ACT": "Acts.",
			"ROM": "Romans.",
			"1CO": "1 Corinthians.",
			"2CO": "2 Corinthians.",
			"GAL": "Galatians.",
			"EPH": "Ephesians.",
			"PHP": "Philippians.",
			"COL": "Colossians.",
			"1TH": "1 Thessalonians.",
			"2TH": "2 Thessalonians.",
			"1TI": "1 Timothy.",
			"2TI": "2 Timothy.",
			"TIT": "Titus.",
			"PHM": "Paul’s Letter to Philemon.",
			"HEB": "Hebrews.",
			"JAS": "James.",
			"1PE": "1 Peter.",
			"2PE": "2 Peter.",
			"1JN": "1 John.",
			"2JN": "John’s Second Letter.",
			"3JN": "John’s Third Letter.",
			"JUD": "The Letter from Jude.",
			"REV": "Revelation."
		},
		"新标点和合本": {
			"GEN": "创世记.",
			"EXO": "出埃及记.",
			"LEV": "利未记.",
			"NUM": "民数记.",
			"DEU": "申命记.",
			"JOS": "约书亚记.",
			"JDG": "士师记.",
			"RUT": "路得记.",
			"1SA": "撒母耳记上.",
			"2SA": "撒母耳记下.",
			"1KI": "列王纪上.",
			"2KI": "列王纪下.",
			"1CH": "历代志上.",
			"2CH": "历代志下.",
			"EZR": "以斯拉记.",
			"NEH": "尼希米记.",
			"EST": "以斯帖记.",
			"JOB": "约伯记.",
			"PSA": "诗篇.",
			"PRO": "箴言.",
			"ECC": "传道书.",
			"SNG": "雅歌.",
			"ISA": "以赛亚书.",
			"JER": "耶利米书.",
			"LAM": "耶利米哀歌.",
			"EZK": "以西结书.",
			"DAN": "但以理书.",
			"HOS": "何西阿书.",
			"JOL": "约珥书.",
			"AMO": "阿摩司书.",
			"OBA": "俄巴底亚书.",
			"JON": "约拿书.",
			"MIC": "弥迦书.",
			"NAM": "那鸿书.",
			"HAB": "哈巴谷书.",
			"ZEP": "西番雅书.",
			"HAG": "哈该书.",
			"ZEC": "撒迦利亚书.",
			"MAL": "玛拉基书.",
			"MAT": "马太福音.",
			"MRK": "马可福音.",
			"LUK": "路加福音.",
			"JHN": "约翰福音.",
			"ACT": "使徒行传.",
			"ROM": "罗马书.",
			"1CO": "哥林多前书.",
			"2CO": "哥林多后书.",
			"GAL": "加拉太书.",
			"EPH": "以弗所书.",
			"PHP": "腓立比书.",
			"COL": "歌罗西书.",
			"1TH": "帖撒罗尼迦前书.",
			"2TH": "帖撒罗尼迦后书.",
			"1TI": "提摩太前书.",
			"2TI": "提摩太后书.",
			"TIT": "提多书.",
			"PHM": "腓利门书.",
			"HEB": "希伯来书.",
			"JAS": "雅各书.",
			"1PE": "彼得前书.",
			"2PE": "彼得后书.",
			"1JN": "约翰一书.",
			"2JN": "约翰二书.",
			"3JN": "约翰三书.",
			"JUD": "犹大书.",
			"REV": "启示录."
		},
		"सरल हिन्दी बाइबल": {
			"GEN": "उत्पत्ति.",
			"EXO": "निर्गमन.",
			"LEV": "लेवी.",
			"NUM": "गणना.",
			"DEU": "व्यवस्था.",
			"JOS": "यहोशू.",
			"JDG": "प्रशासक.",
			"RUT": "रूथ.",
			"1SA": "1 शमुएल.",
			"2SA": "2 शमुएल.",
			"1KI": "1 राजा.",
			"2KI": "2 राजा.",
			"1CH": "1 इतिहास.",
			"2CH": "2 इतिहास.",
			"EZR": "एज़्रा.",
			"NEH": "नेहेमियाह.",
			"EST": "एस्तेर.",
			"JOB": "अय्योब.",
			"PSA": "स्तोत्र.",
			"PRO": "सूक्ति संग्रह.",
			"ECC": "उद्बोधक.",
			"SNG": "सर्वश्रेष्ठ गीत.",
			"ISA": "यशायाह.",
			"JER": "येरेमियाह.",
			"LAM": "विलापगीत.",
			"EZK": "यहेजकेल.",
			"DAN": "दानिएल.",
			"HOS": "होशेआ.",
			"JOL": "योएल.",
			"AMO": "आमोस.",
			"OBA": "ओबदयाह.",
			"JON": "योनाह.",
			"MIC": "मीकाह.",
			"NAM": "नहूम.",
			"HAB": "हबक्कूक.",
			"ZEP": "जेफ़नयाह.",
			"HAG": "हाग्गय.",
			"ZEC": "ज़करयाह.",
			"MAL": "मलाकी.",
			"MAT": "मत्तियाह.",
			"MRK": "मार्कास.",
			"LUK": "लूकॉस.",
			"JHN": "योहन.",
			"ACT": "प्रेरितों.",
			"ROM": "रोमियों.",
			"1CO": "1 कोरिंथ.",
			"2CO": "2 कोरिंथ.",
			"GAL": "गलातिया.",
			"EPH": "इफ़ेसॉस.",
			"PHP": "फ़िलिप्पॉय.",
			"COL": "कोलोस्सॉय.",
			"1TH": "1 थेस्सलोनि.",
			"2TH": "2 थेस्सलोनि.",
			"1TI": "1 तिमोथियॉस.",
			"2TI": "2 तिमोथियॉस.",
			"TIT": "तीतॉस.",
			"PHM": "फ़िलेमोन के नाम पौलॉस का पत्र.",
			"HEB": "इब्री.",
			"JAS": "याकोब.",
			"1PE": "1 पेतरॉस.",
			"2PE": "2 पेतरॉस.",
			"1JN": "1 योहन.",
			"2JN": "योहन का दूसरा पत्र.",
			"3JN": "योहन का तीसरा पत्र.",
			"JUD": "यहूदाह का पत्र.",
			"REV": "प्रकाशन."
		},
		"Santa Biblia libre para el mundo": {
			"GEN": "GÉNESIS.",
			"EXO": "ÉXODO.",
			"LEV": "LEVÍTICO.",
			"NUM": "NÚMEROS.",
			"DEU": "DEUTERONOMIO.",
			"JOS": "JOSUÉ.",
			"JDG": "JUECES.",
			"RUT": "RUT.",
			"1SA": "1 SAMUEL.",
			"2SA": "2 SAMUEL.",
			"1KI": "1 REYES.",
			"2KI": "2 REYES.",
			"1CH": "1 CRÓNICAS.",
			"2CH": "2 CRÓNICAS.",
			"EZR": "ESDRAS.",
			"NEH": "NEHEMÍAS.",
			"EST": "ESTER.",
			"JOB": "JOB.",
			"PSA": "SALMOS.",
			"PRO": "PROVERBIOS.",
			"ECC": "ECLESIASTÉS.",
			"SNG": "CANTARES.",
			"ISA": "ISAÍAS.",
			"JER": "JEREMÍAS.",
			"LAM": "LAMENTACIONES.",
			"EZK": "EZEQUIEL.",
			"DAN": "DANIEL.",
			"HOS": "OSEAS.",
			"JOL": "JOEL.",
			"AMO": "AMÓS.",
			"OBA": "ABDÍAS.",
			"JON": "JONÁS.",
			"MIC": "MIQUEAS.",
			"NAM": "NAHUM.",
			"HAB": "HABACUC.",
			"ZEP": "SOFONÍAS.",
			"HAG": "HAGEO.",
			"ZEC": "ZACARÍAS.",
			"MAL": "MALAQUÍAS.",
			"MAT": "SAN MATEO.",
			"MRK": "SAN MARCOS.",
			"LUK": "SAN LUCAS.",
			"JHN": "SAN JUAN.",
			"ACT": "HECHOS.",
			"ROM": "ROMANOS.",
			"1CO": "1 CORINTIOS.",
			"2CO": "2 CORINTIOS.",
			"GAL": "GÁLATAS.",
			"EPH": "EFESIOS.",
			"PHP": "FILIPENSES.",
			"COL": "COLOSENSES.",
			"1TH": "1 TESALONICENSES.",
			"2TH": "2 TESALONICENSES.",
			"1TI": "1 TIMOTEO.",
			"2TI": "2 TIMOTEO.",
			"TIT": "TITO.",
			"PHM": "LA CARTA DEL APÓSTOL SAN PABLO A FILEMÓN.",
			"HEB": "HEBREOS.",
			"JAS": "SANTIAGO.",
			"1PE": "1 PEDRO.",
			"2PE": "2 PEDRO.",
			"1JN": "1 JUAN.",
			"2JN": "SEGUNDA CARTA DE SAN JUAN APÓSTOL.",
			"3JN": "TERCERA CARTA DE SAN JUAN APÓSTOL.",
			"JUD": "LA CARTA UNIVERSAL DE SAN JUDAS APÓSTOL.",
			"REV": "EL APOCALIPSIS."
		},
		"Sainte Bible libre pour le monde": {
			"GEN": "Genèse.",
			"EXO": "Exode.",
			"LEV": "Lévitique.",
			"NUM": "Numéros.",
			"DEU": "Deutéronome.",
			"JOS": "Josué.",
			"JDG": "Juges.",
			"RUT": "Ruth.",
			"1SA": "1 Samuel.",
			"2SA": "2 Samuel.",
			"1KI": "1 Rois.",
			"2KI": "2 Rois.",
			"1CH": "1 Chroniques.",
			"2CH": "2 Chroniques.",
			"EZR": "Esdras.",
			"NEH": "Néhémie.",
			"EST": "Esther.",
			"JOB": "Job.",
			"PSA": "Psaumes.",
			"PRO": "Proverbes.",
			"ECC": "Ecclésiaste.",
			"SNG": "Cantique.",
			"ISA": "Ésaïe.",
			"JER": "Jérémie.",
			"LAM": "Lamentations.",
			"EZK": "Ézéchiel.",
			"DAN": "Daniel.",
			"HOS": "Osée.",
			"JOL": "Joël.",
			"AMO": "Amos.",
			"OBA": "Le livre du prophète Abdias.",
			"JON": "Jonas.",
			"MIC": "Michée.",
			"NAM": "Nahoum.",
			"HAB": "Habacuc.",
			"ZEP": "Sophonie.",
			"HAG": "Aggée.",
			"ZEC": "Zacharie.",
			"MAL": "Malachie.",
			"MAT": "Matthieu.",
			"MRK": "Marc.",
			"LUK": "Luc.",
			"JHN": "Jean.",
			"ACT": "Actes.",
			"ROM": "Romains.",
			"1CO": "1 Corinthiens.",
			"2CO": "2 Corinthiens.",
			"GAL": "Galates.",
			"EPH": "Éphésiens.",
			"PHP": "Philippiens.",
			"COL": "Colossiens.",
			"1TH": "1 Thessaloniciens.",
			"2TH": "2 Thessaloniciens.",
			"1TI": "1 Timothée.",
			"2TI": "2 Timothée.",
			"TIT": "Tite.",
			"PHM": "La lettre de Paul à Philémon.",
			"HEB": "Hébreux.",
			"JAS": "Jacques.",
			"1PE": "1 Pierre.",
			"2PE": "2 Pierre.",
			"1JN": "1 Jean.",
			"2JN": "La deuxième lettre de Jean.",
			"3JN": "La troisième lettre de Jean.",
			"JUD": "La lettre de Jude.",
			"REV": "Apocalypse."
		},
		"كتاب الحياة": {
			"GEN": "تكوين.",
			"EXO": "خرُوج.",
			"LEV": "لاويّين.",
			"NUM": "عَدَد.",
			"DEU": "تَثنِيَة.",
			"JOS": "يَشُوع.",
			"JDG": "قُضاة.",
			"RUT": "راعُوث.",
			"1SA": "1 صَمُوئيل.",
			"2SA": "2 صَمُوئيل.",
			"1KI": "1 مُلُوك.",
			"2KI": "2 مُلُوك.",
			"1CH": "1 أخبار.",
			"2CH": "2 أخبار.",
			"EZR": "عَزْرا.",
			"NEH": "نَحَمْيا.",
			"EST": "أسْتِير.",
			"JOB": "أيُّوب.",
			"PSA": "مزمور.",
			"PRO": "أمثال.",
			"ECC": "جامِعَة.",
			"SNG": "نشِيد.",
			"ISA": "إشَعْياء.",
			"JER": "إرْمِيا.",
			"LAM": "مَراثِي.",
			"EZK": "حِزْقِيال.",
			"DAN": "دانيال.",
			"HOS": "هُوشَع.",
			"JOL": "يُوئيل.",
			"AMO": "عامُوس.",
			"OBA": "كتابُ عُوبَدْيا.",
			"JON": "يُونان.",
			"MIC": "ميخا.",
			"NAM": "ناحُوم.",
			"HAB": "حَبَقُّوق.",
			"ZEP": "صَفَنْيا.",
			"HAG": "حَجَّي.",
			"ZEC": "زَكَريّا.",
			"MAL": "مَلاخِي.",
			"MAT": "مَتَّى.",
			"MRK": "مَرْقُس.",
			"LUK": "لُوقا.",
			"JHN": "يوحنَّا.",
			"ACT": "أعمال.",
			"ROM": "رُوما.",
			"1CO": "1 كورنثوس.",
			"2CO": "2 كورنثوس.",
			"GAL": "غَلاطِيَّة.",
			"EPH": "أفَسُس.",
			"PHP": "فِيلِبِّي.",
			"COL": "كُولُوسِي.",
			"1TH": "1 تسالونيكي.",
			"2TH": "2 تسالونيكي.",
			"1TI": "1 تيموثاوس.",
			"2TI": "2 تيموثاوس.",
			"TIT": "تِيطُس.",
			"PHM": "الرِّسالَةُ إلَى فِلِيْمُون.",
			"HEB": "عِبرانِيّين.",
			"JAS": "يَعقُوب.",
			"1PE": "1 بطرس.",
			"2PE": "2 بطرس.",
			"1JN": "1 يوحنَّا.",
			"2JN": "رسالَةُ يُوحَنّا الثّانِيَة.",
			"3JN": "رسالَةُ يُوحَنّا الثّالثَة.",
			"JUD": "رسالَةُ يَهُوذا.",
			"REV": "رُؤيا."
		},
		"ইন্ডিয়ান রিভাইজড ভার্সন": {
			"GEN": "আদিপুস্তক.",
			"EXO": "যাত্রাপুস্তক.",
			"LEV": "লেবীয়.",
			"NUM": "গণনা.",
			"DEU": "দ্বিতীয় বিবরণ.",
			"JOS": "যিহোশূয়.",
			"JDG": "বিচারকর্ত্তৃগণ.",
			"RUT": "রূত.",
			"1SA": "1 শমূয়েল.",
			"2SA": "2 শমূয়েল.",
			"1KI": "1 রাজাবলি.",
			"2KI": "2 রাজাবলি.",
			"1CH": "1 বংশাবলি.",
			"2CH": "2 বংশাবলি.",
			"EZR": "ইষ্রা.",
			"NEH": "নহিমিয়.",
			"EST": "ইষ্টের.",
			"JOB": "ইয়োব.",
			"PSA": "গীতসংহিতা.",
			"PRO": "হিতোপদেশ.",
			"ECC": "উপদেশক.",
			"SNG": "পরমগীত.",
			"ISA": "যিশাইয়.",
			"JER": "যিরমিয়.",
			"LAM": "বিলাপ.",
			"EZK": "যিহিস্কেল.",
			"DAN": "দানিয়েল.",
			"HOS": "হোশেয়.",
			"JOL": "যোয়েল.",
			"AMO": "আমোষ.",
			"OBA": "ওবদিয়.",
			"JON": "যোনা.",
			"MIC": "মীখা.",
			"NAM": "নহূম.",
			"HAB": "হবককূক.",
			"ZEP": "সফনিয়.",
			"HAG": "হগয়.",
			"ZEC": "সখরিয়.",
			"MAL": "মালাখি.",
			"MAT": "মথি.",
			"MRK": "মার্ক.",
			"LUK": "লুক.",
			"JHN": "যোহন.",
			"ACT": "প্রেরিতদের কার্য্য.",
			"ROM": "রোমীয়.",
			"1CO": "1 করিন্থীয়.",
			"2CO": "2 করিন্থীয়.",
			"GAL": "গালাতীয়.",
			"EPH": "ইফিষীয়.",
			"PHP": "ফিলিপীয়.",
			"COL": "কলসীয়.",
			"1TH": "1 থিষলনীকীয়.",
			"2TH": "2 থিষলনীকীয়.",
			"1TI": "1 তীমথিয়.",
			"2TI": "2 তীমথিয়.",
			"TIT": "তীত.",
			"PHM": "ফিলীমন.",
			"HEB": "ইব্রীয়.",
			"JAS": "যাকোব.",
			"1PE": "1 পিতর.",
			"2PE": "2 পিতর.",
			"1JN": "1 যোহন.",
			"2JN": "2 যোহন.",
			"3JN": "3 যোহন.",
			"JUD": "যিহূদা.",
			"REV": "প্রকাশিত বাক্য."
		},
		"Синодальный перевод": {
			"GEN": "Бытие.",
			"EXO": "Исход.",
			"LEV": "Левит.",
			"NUM": "Числа.",
			"DEU": "Второзаконие.",
			"JOS": "Книга Иисуса Навина.",
			"JDG": "Книга Судей Израилевых.",
			"RUT": "Книга Руфь.",
			"1SA": "Первая книга Царств.",
			"2SA": "Вторая книга Царств.",
			"1KI": "Третья книга Царств.",
			"2KI": "Четвертая книга Царств.",
			"1CH": "Первая книга Паралипоменон.",
			"2CH": "Вторая книга Паралипоменон.",
			"EZR": "Книга Ездры.",
			"NEH": "Неемия.",
			"EST": "Книга Есфирь.",
			"JOB": "Книга Иова.",
			"PSA": "Псалтырь.",
			"PRO": "Притчи Соломона.",
			"ECC": "Книга Екклесиаста.",
			"SNG": "Песни Песней.",
			"ISA": "Книга пророка Исаии.",
			"JER": "Книга пророка Иеремии.",
			"LAM": "Плач Иеремии.",
			"EZK": "Книга пророка Иезекииля.",
			"DAN": "Книга пророка Даниила.",
			"HOS": "Книга пророка Осии.",
			"JOL": "Книга пророка Иоиля.",
			"AMO": "Книга пророка Амоса.",
			"OBA": "Книга пророка Авдия.",
			"JON": "Книга пророка Ионы.",
			"MIC": "Книга пророка Михея.",
			"NAM": "Книга пророка Наума.",
			"HAB": "Книга пророка Аввакума.",
			"ZEP": "Книга пророка Софонии.",
			"HAG": "Книга пророка Аггея.",
			"ZEC": "Книга пророка Захарии.",
			"MAL": "Книга пророка Малахии.",
			"MAT": "Евангелие от Матфея.",
			"MRK": "Евангелие от Марка.",
			"LUK": "Евангелие от Луки.",
			"JHN": "Евангелие от Иоанна.",
			"ACT": "Деяния.",
			"ROM": "Послание к Римлянам.",
			"1CO": "Первое послание к Коринфянам.",
			"2CO": "Второе послание к Коринфянам.",
			"GAL": "Послание к Галатам.",
			"EPH": "Послание к Ефесянам.",
			"PHP": "Послание к Филлиппийцам.",
			"COL": "Послание к Колоссянам.",
			"1TH": "Первое послание к Фессалоникийцам.",
			"2TH": "Второе послание к Фессалоникийцам.",
			"1TI": "Первое послание к Тимофею.",
			"2TI": "Второе послание к Тимофею.",
			"TIT": "Послание к Титу.",
			"PHM": "Послание к Филимону.",
			"HEB": "Послание к Евреям.",
			"JAS": "Послание Иакова.",
			"1PE": "Первое послание Петра.",
			"2PE": "Второе послание Петра.",
			"1JN": "Первое послание Иоанна.",
			"2JN": "Второе послание Иоанна.",
			"3JN": "Третье послание Иоанна.",
			"JUD": "Послание Иуды.",
			"REV": "Откровение Иоанна Богослова."
		}
	}
};
