var aliases = {
	"codeToLang": {
		"English WEB": {
			"GEN": "Genesis",
			"EXO": "Exodus",
			"LEV": "Leviticus",
			"NUM": "Numbers",
			"DEU": "Deuteronomy",
			"JOS": "Joshua",
			"JDG": "Judges",
			"RUT": "Ruth",
			"1SA": "1 Samuel",
			"2SA": "2 Samuel",
			"1KI": "1 Kings",
			"2KI": "2 Kings",
			"1CH": "1 Chronicles",
			"2CH": "2 Chronicles",
			"EZR": "Ezra",
			"NEH": "Nehemiah",
			"EST": "Esther",
			"JOB": "Job",
			"PSA": "Psalms",
			"PRO": "Proverbs",
			"ECC": "Ecclesiastes",
			"SNG": "Song of Solomon",
			"ISA": "Isaiah",
			"JER": "Jeremiah",
			"LAM": "Lamentations",
			"EZK": "Ezekiel",
			"DAN": "Daniel",
			"HOS": "Hosea",
			"JOL": "Joel",
			"AMO": "Amos",
			"OBA": "Obadiah",
			"JON": "Jonah",
			"MIC": "Micah",
			"NAM": "Nahum",
			"HAB": "Habakkuk",
			"ZEP": "Zephaniah",
			"HAG": "Haggai",
			"ZEC": "Zechariah",
			"MAL": "Malachi",
			"MAT": "Matthew",
			"MRK": "Mark",
			"LUK": "Luke",
			"JHN": "John",
			"ACT": "Acts",
			"ROM": "Romans",
			"1CO": "1 Corinthians",
			"2CO": "2 Corinthians",
			"GAL": "Galatians",
			"EPH": "Ephesians",
			"PHP": "Philippians",
			"COL": "Colossians",
			"1TH": "1 Thessalonians",
			"2TH": "2 Thessalonians",
			"1TI": "1 Timothy",
			"2TI": "2 Timothy",
			"TIT": "Titus",
			"PHM": "Philemon",
			"HEB": "Hebrews",
			"JAS": "James",
			"1PE": "1 Peter",
			"2PE": "2 Peter",
			"1JN": "1 John",
			"2JN": "2 John",
			"3JN": "3 John",
			"JUD": "Jude",
			"REV": "Revelation"
		},
		"English KJV": {
			"GEN": "Genesis",
			"EXO": "Exodus",
			"LEV": "Leviticus",
			"NUM": "Numbers",
			"DEU": "Deuteronomy",
			"JOS": "Joshua",
			"JDG": "Judges",
			"RUT": "Ruth",
			"1SA": "1 Samuel",
			"2SA": "2 Samuel",
			"1KI": "1 Kings",
			"2KI": "2 Kings",
			"1CH": "1 Chronicles",
			"2CH": "2 Chronicles",
			"EZR": "Ezra",
			"NEH": "Nehemiah",
			"EST": "Esther",
			"JOB": "Job",
			"PSA": "Psalms",
			"PRO": "Proverbs",
			"ECC": "Ecclesiastes",
			"SNG": "Song of Solomon",
			"ISA": "Isaiah",
			"JER": "Jeremiah",
			"LAM": "Lamentations",
			"EZK": "Ezekiel",
			"DAN": "Daniel",
			"HOS": "Hosea",
			"JOL": "Joel",
			"AMO": "Amos",
			"OBA": "Obadiah",
			"JON": "Jonah",
			"MIC": "Micah",
			"NAM": "Nahum",
			"HAB": "Habakkuk",
			"ZEP": "Zephaniah",
			"HAG": "Haggai",
			"ZEC": "Zechariah",
			"MAL": "Malachi",
			"MAT": "Matthew",
			"MRK": "Mark",
			"LUK": "Luke",
			"JHN": "John",
			"ACT": "Acts",
			"ROM": "Romans",
			"1CO": "1 Corinthians",
			"2CO": "2 Corinthians",
			"GAL": "Galatians",
			"EPH": "Ephesians",
			"PHP": "Philippians",
			"COL": "Colossians",
			"1TH": "1 Thessalonians",
			"2TH": "2 Thessalonians",
			"1TI": "1 Timothy",
			"2TI": "2 Timothy",
			"TIT": "Titus",
			"PHM": "Philemon",
			"HEB": "Hebrews",
			"JAS": "James",
			"1PE": "1 Peter",
			"2PE": "2 Peter",
			"1JN": "1 John",
			"2JN": "2 John",
			"3JN": "3 John",
			"JUD": "Jude",
			"REV": "Revelation"
		},
		"新标点和合本": {
			"GEN": "创世记.",
			"EXO": "出埃及记.",
			"LEV": "利未记.",
			"NUM": "民数记.",
			"DEU": "申命记.",
			"JOS": "约书亚记.",
			"JDG": "士师记.",
			"RUT": "路得记.",
			"1SA": "撒母耳记上.",
			"2SA": "撒母耳记下.",
			"1KI": "列王纪上.",
			"2KI": "列王纪下.",
			"1CH": "历代志上.",
			"2CH": "历代志下.",
			"EZR": "以斯拉记.",
			"NEH": "尼希米记.",
			"EST": "以斯帖记.",
			"JOB": "约伯记.",
			"PSA": "诗篇.",
			"PRO": "箴言.",
			"ECC": "传道书.",
			"SNG": "雅歌.",
			"ISA": "以赛亚书.",
			"JER": "耶利米书.",
			"LAM": "耶利米哀歌.",
			"EZK": "以西结书.",
			"DAN": "但以理书.",
			"HOS": "何西阿书.",
			"JOL": "约珥书.",
			"AMO": "阿摩司书.",
			"OBA": "俄巴底亚书.",
			"JON": "约拿书.",
			"MIC": "弥迦书.",
			"NAM": "那鸿书.",
			"HAB": "哈巴谷书.",
			"ZEP": "西番雅书.",
			"HAG": "哈该书.",
			"ZEC": "撒迦利亚书.",
			"MAL": "玛拉基书.",
			"MAT": "马太福音.",
			"MRK": "马可福音.",
			"LUK": "路加福音.",
			"JHN": "约翰福音.",
			"ACT": "使徒行传.",
			"ROM": "罗马书.",
			"1CO": "哥林多前书.",
			"2CO": "哥林多后书.",
			"GAL": "加拉太书.",
			"EPH": "以弗所书.",
			"PHP": "腓立比书.",
			"COL": "歌罗西书.",
			"1TH": "帖撒罗尼迦前书.",
			"2TH": "帖撒罗尼迦后书.",
			"1TI": "提摩太前书.",
			"2TI": "提摩太后书.",
			"TIT": "提多书.",
			"PHM": "腓利门书.",
			"HEB": "希伯来书.",
			"JAS": "雅各书.",
			"1PE": "彼得前书.",
			"2PE": "彼得后书.",
			"1JN": "约翰一书.",
			"2JN": "约翰二书.",
			"3JN": "约翰三书.",
			"JUD": "犹大书.",
			"REV": "启示录."
		},
		"सरल हिन्दी बाइबल": {
			"GEN": "उत्पत्ति.",
			"EXO": "निर्गमन.",
			"LEV": "लेवी.",
			"NUM": "गणना.",
			"DEU": "व्यवस्था.",
			"JOS": "यहोशू.",
			"JDG": "प्रशासक.",
			"RUT": "रूथ.",
			"1SA": "1 शमुएल.",
			"2SA": "2 शमुएल.",
			"1KI": "1 राजा.",
			"2KI": "2 राजा.",
			"1CH": "1 इतिहास.",
			"2CH": "2 इतिहास.",
			"EZR": "एज़्रा.",
			"NEH": "नेहेमियाह.",
			"EST": "एस्तेर.",
			"JOB": "अय्योब.",
			"PSA": "स्तोत्र.",
			"PRO": "सूक्ति संग्रह.",
			"ECC": "उद्बोधक.",
			"SNG": "सर्वश्रेष्ठ गीत.",
			"ISA": "यशायाह.",
			"JER": "येरेमियाह.",
			"LAM": "विलापगीत.",
			"EZK": "यहेजकेल.",
			"DAN": "दानिएल.",
			"HOS": "होशेआ.",
			"JOL": "योएल.",
			"AMO": "आमोस.",
			"OBA": "ओबदयाह.",
			"JON": "योनाह.",
			"MIC": "मीकाह.",
			"NAM": "नहूम.",
			"HAB": "हबक्कूक.",
			"ZEP": "जेफ़नयाह.",
			"HAG": "हाग्गय.",
			"ZEC": "ज़करयाह.",
			"MAL": "मलाकी.",
			"MAT": "मत्तियाह.",
			"MRK": "मार्कास.",
			"LUK": "लूकॉस.",
			"JHN": "योहन.",
			"ACT": "प्रेरितों.",
			"ROM": "रोमियों.",
			"1CO": "1 कोरिंथ.",
			"2CO": "2 कोरिंथ.",
			"GAL": "गलातिया.",
			"EPH": "इफ़ेसॉस.",
			"PHP": "फ़िलिप्पॉय.",
			"COL": "कोलोस्सॉय.",
			"1TH": "1 थेस्सलोनि.",
			"2TH": "2 थेस्सलोनि.",
			"1TI": "1 तिमोथियॉस.",
			"2TI": "2 तिमोथियॉस.",
			"TIT": "तीतॉस.",
			"PHM": "फ़िलेमोन के नाम पौलॉस का पत्र.",
			"HEB": "इब्री.",
			"JAS": "याकोब.",
			"1PE": "1 पेतरॉस.",
			"2PE": "2 पेतरॉस.",
			"1JN": "1 योहन.",
			"2JN": "योहन का दूसरा पत्र.",
			"3JN": "योहन का तीसरा पत्र.",
			"JUD": "यहूदाह का पत्र.",
			"REV": "प्रकाशन."
		},
		"Santa Biblia libre para el mundo": {
			"GEN": "GÉNESIS.",
			"EXO": "ÉXODO.",
			"LEV": "LEVÍTICO.",
			"NUM": "NÚMEROS.",
			"DEU": "DEUTERONOMIO.",
			"JOS": "JOSUÉ.",
			"JDG": "JUECES.",
			"RUT": "RUT.",
			"1SA": "1 SAMUEL.",
			"2SA": "2 SAMUEL.",
			"1KI": "1 REYES.",
			"2KI": "2 REYES.",
			"1CH": "1 CRÓNICAS.",
			"2CH": "2 CRÓNICAS.",
			"EZR": "ESDRAS.",
			"NEH": "NEHEMÍAS.",
			"EST": "ESTER.",
			"JOB": "JOB.",
			"PSA": "SALMOS.",
			"PRO": "PROVERBIOS.",
			"ECC": "ECLESIASTÉS.",
			"SNG": "CANTARES.",
			"ISA": "ISAÍAS.",
			"JER": "JEREMÍAS.",
			"LAM": "LAMENTACIONES.",
			"EZK": "EZEQUIEL.",
			"DAN": "DANIEL.",
			"HOS": "OSEAS.",
			"JOL": "JOEL.",
			"AMO": "AMÓS.",
			"OBA": "ABDÍAS.",
			"JON": "JONÁS.",
			"MIC": "MIQUEAS.",
			"NAM": "NAHUM.",
			"HAB": "HABACUC.",
			"ZEP": "SOFONÍAS.",
			"HAG": "HAGEO.",
			"ZEC": "ZACARÍAS.",
			"MAL": "MALAQUÍAS.",
			"MAT": "SAN MATEO.",
			"MRK": "SAN MARCOS.",
			"LUK": "SAN LUCAS.",
			"JHN": "SAN JUAN.",
			"ACT": "HECHOS.",
			"ROM": "ROMANOS.",
			"1CO": "1 CORINTIOS.",
			"2CO": "2 CORINTIOS.",
			"GAL": "GÁLATAS.",
			"EPH": "EFESIOS.",
			"PHP": "FILIPENSES.",
			"COL": "COLOSENSES.",
			"1TH": "1 TESALONICENSES.",
			"2TH": "2 TESALONICENSES.",
			"1TI": "1 TIMOTEO.",
			"2TI": "2 TIMOTEO.",
			"TIT": "TITO.",
			"PHM": "LA CARTA DEL APÓSTOL SAN PABLO A FILEMÓN.",
			"HEB": "HEBREOS.",
			"JAS": "SANTIAGO.",
			"1PE": "1 PEDRO.",
			"2PE": "2 PEDRO.",
			"1JN": "1 JUAN.",
			"2JN": "SEGUNDA CARTA DE SAN JUAN APÓSTOL.",
			"3JN": "TERCERA CARTA DE SAN JUAN APÓSTOL.",
			"JUD": "LA CARTA UNIVERSAL DE SAN JUDAS APÓSTOL.",
			"REV": "EL APOCALIPSIS."
		},
		"Sainte Bible libre pour le monde": {
			"GEN": "Genèse.",
			"EXO": "Exode.",
			"LEV": "Lévitique.",
			"NUM": "Numéros.",
			"DEU": "Deutéronome.",
			"JOS": "Josué.",
			"JDG": "Juges.",
			"RUT": "Ruth.",
			"1SA": "1 Samuel.",
			"2SA": "2 Samuel.",
			"1KI": "1 Rois.",
			"2KI": "2 Rois.",
			"1CH": "1 Chroniques.",
			"2CH": "2 Chroniques.",
			"EZR": "Esdras.",
			"NEH": "Néhémie.",
			"EST": "Esther.",
			"JOB": "Job.",
			"PSA": "Psaumes.",
			"PRO": "Proverbes.",
			"ECC": "Ecclésiaste.",
			"SNG": "Cantique.",
			"ISA": "Ésaïe.",
			"JER": "Jérémie.",
			"LAM": "Lamentations.",
			"EZK": "Ézéchiel.",
			"DAN": "Daniel.",
			"HOS": "Osée.",
			"JOL": "Joël.",
			"AMO": "Amos.",
			"OBA": "Le livre du prophète Abdias.",
			"JON": "Jonas.",
			"MIC": "Michée.",
			"NAM": "Nahoum.",
			"HAB": "Habacuc.",
			"ZEP": "Sophonie.",
			"HAG": "Aggée.",
			"ZEC": "Zacharie.",
			"MAL": "Malachie.",
			"MAT": "Matthieu.",
			"MRK": "Marc.",
			"LUK": "Luc.",
			"JHN": "Jean.",
			"ACT": "Actes.",
			"ROM": "Romains.",
			"1CO": "1 Corinthiens.",
			"2CO": "2 Corinthiens.",
			"GAL": "Galates.",
			"EPH": "Éphésiens.",
			"PHP": "Philippiens.",
			"COL": "Colossiens.",
			"1TH": "1 Thessaloniciens.",
			"2TH": "2 Thessaloniciens.",
			"1TI": "1 Timothée.",
			"2TI": "2 Timothée.",
			"TIT": "Tite.",
			"PHM": "La lettre de Paul à Philémon.",
			"HEB": "Hébreux.",
			"JAS": "Jacques.",
			"1PE": "1 Pierre.",
			"2PE": "2 Pierre.",
			"1JN": "1 Jean.",
			"2JN": "La deuxième lettre de Jean.",
			"3JN": "La troisième lettre de Jean.",
			"JUD": "La lettre de Jude.",
			"REV": "Apocalypse."
		},
		"كتاب الحياة": {
			"GEN": "تكوين.",
			"EXO": "خرُوج.",
			"LEV": "لاويّين.",
			"NUM": "عَدَد.",
			"DEU": "تَثنِيَة.",
			"JOS": "يَشُوع.",
			"JDG": "قُضاة.",
			"RUT": "راعُوث.",
			"1SA": "1 صَمُوئيل.",
			"2SA": "2 صَمُوئيل.",
			"1KI": "1 مُلُوك.",
			"2KI": "2 مُلُوك.",
			"1CH": "1 أخبار.",
			"2CH": "2 أخبار.",
			"EZR": "عَزْرا.",
			"NEH": "نَحَمْيا.",
			"EST": "أسْتِير.",
			"JOB": "أيُّوب.",
			"PSA": "مزمور.",
			"PRO": "أمثال.",
			"ECC": "جامِعَة.",
			"SNG": "نشِيد.",
			"ISA": "إشَعْياء.",
			"JER": "إرْمِيا.",
			"LAM": "مَراثِي.",
			"EZK": "حِزْقِيال.",
			"DAN": "دانيال.",
			"HOS": "هُوشَع.",
			"JOL": "يُوئيل.",
			"AMO": "عامُوس.",
			"OBA": "كتابُ عُوبَدْيا.",
			"JON": "يُونان.",
			"MIC": "ميخا.",
			"NAM": "ناحُوم.",
			"HAB": "حَبَقُّوق.",
			"ZEP": "صَفَنْيا.",
			"HAG": "حَجَّي.",
			"ZEC": "زَكَريّا.",
			"MAL": "مَلاخِي.",
			"MAT": "مَتَّى.",
			"MRK": "مَرْقُس.",
			"LUK": "لُوقا.",
			"JHN": "يوحنَّا.",
			"ACT": "أعمال.",
			"ROM": "رُوما.",
			"1CO": "1 كورنثوس.",
			"2CO": "2 كورنثوس.",
			"GAL": "غَلاطِيَّة.",
			"EPH": "أفَسُس.",
			"PHP": "فِيلِبِّي.",
			"COL": "كُولُوسِي.",
			"1TH": "1 تسالونيكي.",
			"2TH": "2 تسالونيكي.",
			"1TI": "1 تيموثاوس.",
			"2TI": "2 تيموثاوس.",
			"TIT": "تِيطُس.",
			"PHM": "الرِّسالَةُ إلَى فِلِيْمُون.",
			"HEB": "عِبرانِيّين.",
			"JAS": "يَعقُوب.",
			"1PE": "1 بطرس.",
			"2PE": "2 بطرس.",
			"1JN": "1 يوحنَّا.",
			"2JN": "رسالَةُ يُوحَنّا الثّانِيَة.",
			"3JN": "رسالَةُ يُوحَنّا الثّالثَة.",
			"JUD": "رسالَةُ يَهُوذا.",
			"REV": "رُؤيا."
		},
		"ইন্ডিয়ান রিভাইজড ভার্সন": {
			"GEN": "আদিপুস্তক.",
			"EXO": "যাত্রাপুস্তক.",
			"LEV": "লেবীয়.",
			"NUM": "গণনা.",
			"DEU": "দ্বিতীয় বিবরণ.",
			"JOS": "যিহোশূয়.",
			"JDG": "বিচারকর্ত্তৃগণ.",
			"RUT": "রূত.",
			"1SA": "1 শমূয়েল.",
			"2SA": "2 শমূয়েল.",
			"1KI": "1 রাজাবলি.",
			"2KI": "2 রাজাবলি.",
			"1CH": "1 বংশাবলি.",
			"2CH": "2 বংশাবলি.",
			"EZR": "ইষ্রা.",
			"NEH": "নহিমিয়.",
			"EST": "ইষ্টের.",
			"JOB": "ইয়োব.",
			"PSA": "গীতসংহিতা.",
			"PRO": "হিতোপদেশ.",
			"ECC": "উপদেশক.",
			"SNG": "পরমগীত.",
			"ISA": "যিশাইয়.",
			"JER": "যিরমিয়.",
			"LAM": "বিলাপ.",
			"EZK": "যিহিস্কেল.",
			"DAN": "দানিয়েল.",
			"HOS": "হোশেয়.",
			"JOL": "যোয়েল.",
			"AMO": "আমোষ.",
			"OBA": "ওবদিয়.",
			"JON": "যোনা.",
			"MIC": "মীখা.",
			"NAM": "নহূম.",
			"HAB": "হবককূক.",
			"ZEP": "সফনিয়.",
			"HAG": "হগয়.",
			"ZEC": "সখরিয়.",
			"MAL": "মালাখি.",
			"MAT": "মথি.",
			"MRK": "মার্ক.",
			"LUK": "লুক.",
			"JHN": "যোহন.",
			"ACT": "প্রেরিতদের কার্য্য.",
			"ROM": "রোমীয়.",
			"1CO": "1 করিন্থীয়.",
			"2CO": "2 করিন্থীয়.",
			"GAL": "গালাতীয়.",
			"EPH": "ইফিষীয়.",
			"PHP": "ফিলিপীয়.",
			"COL": "কলসীয়.",
			"1TH": "1 থিষলনীকীয়.",
			"2TH": "2 থিষলনীকীয়.",
			"1TI": "1 তীমথিয়.",
			"2TI": "2 তীমথিয়.",
			"TIT": "তীত.",
			"PHM": "ফিলীমন.",
			"HEB": "ইব্রীয়.",
			"JAS": "যাকোব.",
			"1PE": "1 পিতর.",
			"2PE": "2 পিতর.",
			"1JN": "1 যোহন.",
			"2JN": "2 যোহন.",
			"3JN": "3 যোহন.",
			"JUD": "যিহূদা.",
			"REV": "প্রকাশিত বাক্য."
		},
		"Синодальный перевод": {
			"GEN": "Бытие.",
			"EXO": "Исход.",
			"LEV": "Левит.",
			"NUM": "Числа.",
			"DEU": "Второзаконие.",
			"JOS": "Книга Иисуса Навина.",
			"JDG": "Книга Судей Израилевых.",
			"RUT": "Книга Руфь.",
			"1SA": "Первая книга Царств.",
			"2SA": "Вторая книга Царств.",
			"1KI": "Третья книга Царств.",
			"2KI": "Четвертая книга Царств.",
			"1CH": "Первая книга Паралипоменон.",
			"2CH": "Вторая книга Паралипоменон.",
			"EZR": "Книга Ездры.",
			"NEH": "Неемия.",
			"EST": "Книга Есфирь.",
			"JOB": "Книга Иова.",
			"PSA": "Псалтырь.",
			"PRO": "Притчи Соломона.",
			"ECC": "Книга Екклесиаста.",
			"SNG": "Песни Песней.",
			"ISA": "Книга пророка Исаии.",
			"JER": "Книга пророка Иеремии.",
			"LAM": "Плач Иеремии.",
			"EZK": "Книга пророка Иезекииля.",
			"DAN": "Книга пророка Даниила.",
			"HOS": "Книга пророка Осии.",
			"JOL": "Книга пророка Иоиля.",
			"AMO": "Книга пророка Амоса.",
			"OBA": "Книга пророка Авдия.",
			"JON": "Книга пророка Ионы.",
			"MIC": "Книга пророка Михея.",
			"NAM": "Книга пророка Наума.",
			"HAB": "Книга пророка Аввакума.",
			"ZEP": "Книга пророка Софонии.",
			"HAG": "Книга пророка Аггея.",
			"ZEC": "Книга пророка Захарии.",
			"MAL": "Книга пророка Малахии.",
			"MAT": "Евангелие от Матфея.",
			"MRK": "Евангелие от Марка.",
			"LUK": "Евангелие от Луки.",
			"JHN": "Евангелие от Иоанна.",
			"ACT": "Деяния.",
			"ROM": "Послание к Римлянам.",
			"1CO": "Первое послание к Коринфянам.",
			"2CO": "Второе послание к Коринфянам.",
			"GAL": "Послание к Галатам.",
			"EPH": "Послание к Ефесянам.",
			"PHP": "Послание к Филлиппийцам.",
			"COL": "Послание к Колоссянам.",
			"1TH": "Первое послание к Фессалоникийцам.",
			"2TH": "Второе послание к Фессалоникийцам.",
			"1TI": "Первое послание к Тимофею.",
			"2TI": "Второе послание к Тимофею.",
			"TIT": "Послание к Титу.",
			"PHM": "Послание к Филимону.",
			"HEB": "Послание к Евреям.",
			"JAS": "Послание Иакова.",
			"1PE": "Первое послание Петра.",
			"2PE": "Второе послание Петра.",
			"1JN": "Первое послание Иоанна.",
			"2JN": "Второе послание Иоанна.",
			"3JN": "Третье послание Иоанна.",
			"JUD": "Послание Иуды.",
			"REV": "Откровение Иоанна Богослова."
		}
	}
};
